### ISSUE TITLE
To improve image quality, quality or imageQuality options dont work

### ISSUE THREAD

**Issue by KkSaSr** [timstudd/node-wkhtmltoimage#6]
I tried genrating image from html, but the quality is not so good. To improve the quality, i tried adding quality option as 200 but the image quality dint improve, then i tried imageQuality and that returned an error code. How do i improv the quality of the generated image?

**Comment by timstudd** [comment]
@KkSaSr Can you please provide your use of wkhtmltoimage?  The `quality` option accepts values of 0-100, but other options such as the output image format and dimensions (`height` and `width`) will impact the generated image quality.

Here's some helpful information about wkhtmltoimage options: http://madalgo.au.dk/~jakobt/wkhtmltoxdoc/wkhtmltoimage_0.10.0_rc2-doc.html
