### ISSUE TITLE
Calling `generate` with html does not work.

### ISSUE THREAD

**Issue by Andrew1431** [timstudd/node-wkhtmltoimage#7]
Hey there! I'm attempting to call `wkhtmltoimage.generate('<p>Some html</p>')` but it's just returning an empty buffer with no data. If I put the same data into an html file and use the CLI with file name options, the stream outputs as expected. 

Any clue on how to fix this issue?

**Comment by ivands** [comment]
Same problem.

**Comment by Andrew1431** [comment]
Crap I'm one of those people who didn't supply the answer to the question they asked >.< this was 4 years ago too so there's no chance I'd remember.
